### ISSUE TITLE
More timestamps for S1?

### ISSUE THREAD

**Issue by neteler** [Sijoma/openeo-sentinel-referencedata#3]
At time I see one UUID listed for S1. As the pilot use case is a multitemporal analysis, shouldn't there be more? Just asking, probably I'm missing something.

Thanks

**Comment by Sijoma** [comment]
Yes, you are right. There should be more Sentinel-1 and also 3 data.

Currently, I have a strong focus on validating the results of the analysis of Sentinel-2 data and thus focused on selecting Sentinel-2 imagery with additional overlapping Sentinel-1 and 3 tiles for Europe.

Do you have a process graph as an example use case? That would help me greatly. Unfortunately, the example of the API version 0.3.1 does not work anymore as the process "aggregate_time" is not available on the EURAC and GEE OpenEO back-ends. Without that process, I only get an almost complete blue image.

**Comment by neteler** [comment]
We are currently working on the process graph for pilot use case 1 (Sentinel-1 RGB composite), coming soon...

**Comment by neteler** [comment]
Shall we pick "random" areas? This issue currently blocks us...

**Comment by Sijoma** [comment]
Yes, you can pick random areas. I thought there might be something better than that if someone has more in-depth knowledge about S1 imagery. If you do not have the time I will be able to do it in the next two days or so.

**Comment by m-mohr** [comment]
@neteler Yes, this repository is currently only meant to provide common data for back-end validation and has no impact on the use cases (yet?).
@Sijoma It would be sensible if the validation data would be aligned to the use cases though. This would have to align with EODC/TUW, too.

**Comment by neteler** [comment]
@m-mohr yes, I had the showcase preparation for the upcoming EODC/TUW in mind

**Comment by m-mohr** [comment]
@neteler I didn't meant the showcase, but that it's their use case according to the project proposal. So which data to include has to be chosen according to the project proposal / together with EODC/TUW. Not sure which dataset was agreed on to be used for the showcase, but it is not this one (I think). Depends on what other providers have available, but that's something to discuss with the showcase back-ends, i.e. EURAC/EODC/VITO.
